import React from 'react';
import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { ThumbnailDetailDrawer } from '../ThumbnailDetailDrawer';
import { usePublicThumbnailGenerator } from '../../../../../hooks/usePublicThumbnailGenerator';
import { thumbnailApi } from '../../../../../api/thumbnail';
jest.mock('../../../../../hooks/usePublicThumbnailGenerator');
jest.mock('../../../../../api/thumbnail', () => ({ thumbnailApi: { refineThumbnailConversationally: jest.fn() } }));
jest.mock('../ViralSharePopup', () => ({ ViralSharePopup: () => null }));
it('keeps edit history when reopened and downloads the selected version at its original aspect ratio', async () => {
  window.matchMedia = jest.fn(() => ({ matches: false, addListener: jest.fn(), removeListener: jest.fn() })) as any;
  const download = jest.fn().mockResolvedValue(undefined);
  (usePublicThumbnailGenerator as jest.Mock).mockReturnValue({ isAuthenticated: true, needsEmailCapture: false, downloadThumbnail: download, clearError: jest.fn() });
  (thumbnailApi.refineThumbnailConversationally as jest.Mock).mockResolvedValue({ data: { thumbnailUrl: 'https://example.com/edited.png' } });
  const thumbnail = { id: 123, prompt: 'Camera', imageUrl: 'https://example.com/original.png', createdAt: '2026-09-09', size: 'short' as const };
  const close = jest.fn();
  const view = render(<ThumbnailDetailDrawer thumbnail={thumbnail} isOpen onClose={close} />);
  fireEvent.change(screen.getByLabelText('Edit instruction'), { target: { value: 'Blue background' } });
  fireEvent.click(screen.getByRole('button', { name: 'Apply edit' }));
  await waitFor(() => expect(screen.getByAltText('AI generated thumbnail')).toHaveAttribute('src', 'https://example.com/edited.png'));
  expect(thumbnailApi.refineThumbnailConversationally).toHaveBeenCalledWith(expect.objectContaining({ imageUrl: thumbnail.imageUrl, size: 'short' }));
  fireEvent.click(screen.getByRole('button', { name: 'Download image' }));
  expect(download).toHaveBeenCalledWith('edited', 'https://example.com/edited.png');
  view.rerender(<ThumbnailDetailDrawer thumbnail={thumbnail} isOpen={false} onClose={close} />);
  expect(screen.queryByRole('dialog')).not.toBeInTheDocument();
  view.rerender(<ThumbnailDetailDrawer thumbnail={thumbnail} isOpen onClose={close} />);
  expect(screen.getByAltText('AI generated thumbnail')).toHaveAttribute('src', 'https://example.com/edited.png');
  fireEvent.click(screen.getByRole('button', { name: 'Undo' }));
  expect(screen.getByAltText('AI generated thumbnail')).toHaveAttribute('src', thumbnail.imageUrl);
  expect(screen.getByLabelText('Thumbnail version')).toHaveValue('0');
});
