import React from 'react';
import { act, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import GeneratePage from '../GeneratePage';
import useCTREngine from '../../../../hooks/useCTREngine';
import { usePublicThumbnailGenerator } from '../../../../hooks/usePublicThumbnailGenerator';
jest.mock('../../../../hooks/useCTREngine', () => ({ __esModule: true, default: jest.fn() }));
jest.mock('../../../../hooks/usePublicThumbnailGenerator', () => ({ usePublicThumbnailGenerator: jest.fn() }));
jest.mock('../AIThumbnailsLayout', () => ({ __esModule: true, default: ({ children }: any) => <>{children}</> }));
jest.mock('../../../common/ThumbnailPackaging', () => ({ ThumbnailStylePicker: ({ onChange }: any) => <button type="button" onClick={() => onChange(7, true)}>Music style</button> }));
jest.mock('../../../common/ThumbnailLogoPicker', () => ({ ThumbnailLogoPicker: ({ savedLogo }: any) => <span>{savedLogo ? 'Saved logo included' : 'No logo'}</span> }));
jest.mock('../../../common/ThumbnailSubjectPicker', () => ({ ThumbnailSubjectPicker: ({ onChange }: any) => <button type="button" onClick={() => onChange([new File(['x'], 'subject.png', { type: 'image/png' })])}>Add reference</button> }));
jest.mock('../components/ThumbnailFormatSelector', () => ({ ThumbnailFormatSelector: ({ onFormatChange }: any) => <button type="button" onClick={() => onFormatChange('short')}>Portrait</button> }));
jest.mock('../components/NicheSelector', () => ({ NicheSelector: () => null }));
jest.mock('../components/BuyCreditsModal', () => ({ BuyCreditsModal: () => null }));
jest.mock('../components/ThumbnailDetailDrawer', () => ({ ThumbnailDetailDrawer: () => null }));
jest.mock('../components/GeneratedConceptsGrid', () => ({ GeneratedConceptsGrid: ({ onClear, outputFormat, auditContext }: any) => { const [edited, edit] = require('react').useState(false); return <div><span>{edited ? 'Edited result' : 'Original result'}</span><span>{outputFormat}</span><span>{auditContext.title}</span><button onClick={() => edit(true)}>Test edit</button><button onClick={onClear}>Edit brief</button></div>; } }));
const pricing = { ctr: { generatePerConcept: 15 }, thumbnail: { generatePerImage: 12, editPerImage: 18 } };
let ctr: any;
let creative: any;
beforeEach(() => {
  window.matchMedia = jest.fn(() => ({ matches: true })) as any;
  ctr = { isAuthenticated: true, generatedConcepts: [], generationProgress: { status: 'idle' }, usageAccess: { mode: 'credits', pricing, creditInfo: { available: 100 } }, isLoadingQuota: false, generateThumbnails: jest.fn().mockResolvedValue(undefined), clearError: jest.fn(), refreshQuota: jest.fn(), niches: [] };
  creative = { latestThumbnails: [], thumbnails: [], usageMode: 'quota', quotaInfo: { remaining: 3 }, generateThumbnail: jest.fn().mockResolvedValue(undefined), clearError: jest.fn(), refreshQuota: jest.fn() };
  (useCTREngine as jest.Mock).mockImplementation(() => ctr);
  (usePublicThumbnailGenerator as jest.Mock).mockImplementation(() => creative);
});
const page = () => <MemoryRouter><GeneratePage /></MemoryRouter>;
it('submits one brief with visual direction, saved logo, subjects and explicit cost', async () => {
  render(page());
  expect(screen.queryByRole('button', { name: 'Optimized' })).not.toBeInTheDocument();
  expect(screen.getByRole('button', { name: 'Generate 2 concepts · 30 credits' })).toBeDisabled();
  fireEvent.change(screen.getByLabelText('Video title or idea'), { target: { value: 'AI jobs' } });
  fireEvent.change(screen.getByLabelText('Creator hook'), { target: { value: 'Who gets the gains?' } });
  fireEvent.change(screen.getByLabelText('Visual direction'), { target: { value: 'Quiet cinematic scene' } });
  fireEvent.click(screen.getByText('Music style'));
  expect(screen.getByText('Saved logo included')).toBeInTheDocument();
  fireEvent.click(screen.getByText('Add reference'));
  fireEvent.click(screen.getByRole('button', { name: 'Generate 2 concepts · 30 credits' }));
  await waitFor(() => expect(ctr.generateThumbnails).toHaveBeenCalledTimes(1));
  expect(ctr.generateThumbnails).toHaveBeenCalledWith(expect.objectContaining({ title: 'AI jobs', concepts: 2, savedStyleId: 7, subjectReferences: [expect.any(File)], creatorBrief: expect.objectContaining({ title: 'AI jobs', creatorHook: 'Who gets the gains?', description: expect.stringContaining('Quiet cinematic scene') }) }));
});
it('keeps the brief, result format and edited results when moving back and forth', async () => {
  const view = render(page());
  fireEvent.change(screen.getByLabelText('Video title or idea'), { target: { value: 'Original title' } });
  fireEvent.click(screen.getByRole('button', { name: 'Generate 2 concepts · 30 credits' }));
  await waitFor(() => expect(ctr.generateThumbnails).toHaveBeenCalled());
  ctr.generatedConcepts = [{ id: '7', thumbnailUrl: 'image.png' }];
  view.rerender(page());
  await screen.findByRole('button', { name: 'Edit brief' });
  fireEvent.click(screen.getByText('Test edit'));
  fireEvent.click(screen.getByText('Edit brief'));
  expect(screen.getByLabelText('Video title or idea')).toHaveValue('Original title');
  fireEvent.change(screen.getByLabelText('Video title or idea'), { target: { value: 'Next title' } });
  fireEvent.click(screen.getByText('Portrait'));
  fireEvent.click(screen.getByRole('button', { name: '2. Choose' }));
  expect(screen.getByText('Edited result')).toBeVisible();
  expect(screen.getByText('Original title')).toBeVisible();
  expect(screen.getByText('landscape')).toBeVisible();
});
it('prevents duplicate generation and retains inputs after a failed request', async () => {
  let finish!: () => void;
  ctr.generateThumbnails.mockImplementation(() => new Promise<void>(resolve => { finish = resolve; }));
  render(page());
  fireEvent.change(screen.getByLabelText('Video title or idea'), { target: { value: 'Ocean music' } });
  fireEvent.submit(screen.getByRole('form', { name: 'Thumbnail brief' }));
  fireEvent.submit(screen.getByRole('form', { name: 'Thumbnail brief' }));
  expect(ctr.generateThumbnails).toHaveBeenCalledTimes(1);
  await act(async () => finish());
  expect(screen.getByLabelText('Video title or idea')).toHaveValue('Ocean music');
  expect(screen.getByRole('button', { name: 'Generate 2 concepts · 30 credits' })).toBeEnabled();
});
it('preserves the anonymous generation path', async () => {
  ctr.isAuthenticated = false;
  render(page());
  fireEvent.change(screen.getByLabelText('Video title or idea'), { target: { value: 'Ocean music' } });
  fireEvent.click(screen.getByRole('button', { name: 'Generate 2 concepts' }));
  await waitFor(() => expect(creative.generateThumbnail).toHaveBeenCalledWith('Ocean music', expect.objectContaining({ n: 2, size: 'landscape' })));
  expect(ctr.generateThumbnails).not.toHaveBeenCalled();
});
it('blocks credit spending until pricing loads and when the balance is insufficient', () => {
  ctr.usageAccess = { mode: 'credits', pricing: null, creditInfo: { available: 100 } };
  const view = render(page());
  fireEvent.change(screen.getByLabelText('Video title or idea'), { target: { value: 'Ocean music' } });
  expect(screen.getByRole('button', { name: 'Generate 2 concepts' })).toBeDisabled();
  ctr.usageAccess = { mode: 'credits', pricing, creditInfo: { available: 20 } };
  view.rerender(page());
  expect(screen.getByRole('button', { name: 'Generate 2 concepts · 30 credits' })).toBeDisabled();
  fireEvent.change(screen.getByLabelText('Number of concepts'), { target: { value: '1' } });
  expect(screen.getByRole('button', { name: 'Generate 1 concept · 15 credits' })).toBeEnabled();
});
